---
- name: configuration 
  hosts: all
  user: ubuntu
  become: true
  gather_facts: false

  vars:
     ansible_python_interpreter: /usr/bin/python3
     ansible_host_key_checking: false
     nsible_stdout_callback: yaml
     environment:
       TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
       TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
       TYPEORM_PORT: "{{ lookup('env','TYPEORM_'TYPEORM_PORT') }}"
       TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
       TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
       TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
       TYPEORM_MIGRATIONS: .src/migrations/*.ts
       TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts

  

  pre_tasks:
    - name: "wait for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 100

    - name: "install python for Ansible."
      become: true
      apt:
        name: ["python3"]
        state: latest
        update_cache: yes
        
 

  roles:
    - configure-server
    - configure-prometheus-node-exporter
