---
- name: "configuration play."
  hosts: web
  user: ec2-user
  become: true
  gather_facts: false
  
 pre_tasks:
      name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
      name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false 
      setup:

 vars:
     ansible_python_interpreter: /usr/bin/python3
     ansible_host_key_checking: false
     nsible_stdout_callback: yaml
     environment:
       TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
       TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
       TYPEORM_PORT: "{{ lookup('env','TYPEORM_'TYPEORM_PORT') }}"
       TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
       TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
       TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
       TYPEORM_MIGRATIONS: .src/migrations/*.ts
       TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts

  

   

 

  roles:
    - configure-server
    - configure-prometheus-node-exporter
